/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreatorNameRouteImport } from './routes/creator/$name'
import { Route as ApiPublicRedditRouteImport } from './routes/api/public/reddit'
import { Route as ApiPublicMediaRouteImport } from './routes/api/public/media'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as ApiPublicRedditUserRouteImport } from './routes/api/public/reddit/user'
import { Route as ApiPublicRedditMixRouteImport } from './routes/api/public/reddit/mix'
import { Route as ApiPublicMediaResolveRouteImport } from './routes/api/public/media/resolve'
import { Route as ApiPublicAuthStatusRouteImport } from './routes/api/public/auth/status'
import { Route as ApiPublicAuthPinRouteImport } from './routes/api/public/auth/pin'
import { Route as ApiPublicAuthLogoutRouteImport } from './routes/api/public/auth/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorNameRoute = CreatorNameRouteImport.update({
  id: '/creator/$name',
  path: '/creator/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedditRoute = ApiPublicRedditRouteImport.update({
  id: '/api/public/reddit',
  path: '/api/public/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaRoute = ApiPublicMediaRouteImport.update({
  id: '/api/public/media',
  path: '/api/public/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedditUserRoute = ApiPublicRedditUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => ApiPublicRedditRoute,
} as any)
const ApiPublicRedditMixRoute = ApiPublicRedditMixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => ApiPublicRedditRoute,
} as any)
const ApiPublicMediaResolveRoute = ApiPublicMediaResolveRouteImport.update({
  id: '/resolve',
  path: '/resolve',
  getParentRoute: () => ApiPublicMediaRoute,
} as any)
const ApiPublicAuthStatusRoute = ApiPublicAuthStatusRouteImport.update({
  id: '/api/public/auth/status',
  path: '/api/public/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthPinRoute = ApiPublicAuthPinRouteImport.update({
  id: '/api/public/auth/pin',
  path: '/api/public/auth/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLogoutRoute = ApiPublicAuthLogoutRouteImport.update({
  id: '/api/public/auth/logout',
  path: '/api/public/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creator/$name': typeof CreatorNameRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/media': typeof ApiPublicMediaRouteWithChildren
  '/api/public/reddit': typeof ApiPublicRedditRouteWithChildren
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/api/public/auth/pin': typeof ApiPublicAuthPinRoute
  '/api/public/auth/status': typeof ApiPublicAuthStatusRoute
  '/api/public/media/resolve': typeof ApiPublicMediaResolveRoute
  '/api/public/reddit/mix': typeof ApiPublicRedditMixRoute
  '/api/public/reddit/user': typeof ApiPublicRedditUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creator/$name': typeof CreatorNameRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/media': typeof ApiPublicMediaRouteWithChildren
  '/api/public/reddit': typeof ApiPublicRedditRouteWithChildren
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/api/public/auth/pin': typeof ApiPublicAuthPinRoute
  '/api/public/auth/status': typeof ApiPublicAuthStatusRoute
  '/api/public/media/resolve': typeof ApiPublicMediaResolveRoute
  '/api/public/reddit/mix': typeof ApiPublicRedditMixRoute
  '/api/public/reddit/user': typeof ApiPublicRedditUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creator/$name': typeof CreatorNameRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/media': typeof ApiPublicMediaRouteWithChildren
  '/api/public/reddit': typeof ApiPublicRedditRouteWithChildren
  '/api/public/auth/logout': typeof ApiPublicAuthLogoutRoute
  '/api/public/auth/pin': typeof ApiPublicAuthPinRoute
  '/api/public/auth/status': typeof ApiPublicAuthStatusRoute
  '/api/public/media/resolve': typeof ApiPublicMediaResolveRoute
  '/api/public/reddit/mix': typeof ApiPublicRedditMixRoute
  '/api/public/reddit/user': typeof ApiPublicRedditUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creator/$name'
    | '/api/public/image'
    | '/api/public/media'
    | '/api/public/reddit'
    | '/api/public/auth/logout'
    | '/api/public/auth/pin'
    | '/api/public/auth/status'
    | '/api/public/media/resolve'
    | '/api/public/reddit/mix'
    | '/api/public/reddit/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/creator/$name'
    | '/api/public/image'
    | '/api/public/media'
    | '/api/public/reddit'
    | '/api/public/auth/logout'
    | '/api/public/auth/pin'
    | '/api/public/auth/status'
    | '/api/public/media/resolve'
    | '/api/public/reddit/mix'
    | '/api/public/reddit/user'
  id:
    | '__root__'
    | '/'
    | '/creator/$name'
    | '/api/public/image'
    | '/api/public/media'
    | '/api/public/reddit'
    | '/api/public/auth/logout'
    | '/api/public/auth/pin'
    | '/api/public/auth/status'
    | '/api/public/media/resolve'
    | '/api/public/reddit/mix'
    | '/api/public/reddit/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreatorNameRoute: typeof CreatorNameRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
  ApiPublicMediaRoute: typeof ApiPublicMediaRouteWithChildren
  ApiPublicRedditRoute: typeof ApiPublicRedditRouteWithChildren
  ApiPublicAuthLogoutRoute: typeof ApiPublicAuthLogoutRoute
  ApiPublicAuthPinRoute: typeof ApiPublicAuthPinRoute
  ApiPublicAuthStatusRoute: typeof ApiPublicAuthStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$name': {
      id: '/creator/$name'
      path: '/creator/$name'
      fullPath: '/creator/$name'
      preLoaderRoute: typeof CreatorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reddit': {
      id: '/api/public/reddit'
      path: '/api/public/reddit'
      fullPath: '/api/public/reddit'
      preLoaderRoute: typeof ApiPublicRedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media': {
      id: '/api/public/media'
      path: '/api/public/media'
      fullPath: '/api/public/media'
      preLoaderRoute: typeof ApiPublicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reddit/user': {
      id: '/api/public/reddit/user'
      path: '/user'
      fullPath: '/api/public/reddit/user'
      preLoaderRoute: typeof ApiPublicRedditUserRouteImport
      parentRoute: typeof ApiPublicRedditRoute
    }
    '/api/public/reddit/mix': {
      id: '/api/public/reddit/mix'
      path: '/mix'
      fullPath: '/api/public/reddit/mix'
      preLoaderRoute: typeof ApiPublicRedditMixRouteImport
      parentRoute: typeof ApiPublicRedditRoute
    }
    '/api/public/media/resolve': {
      id: '/api/public/media/resolve'
      path: '/resolve'
      fullPath: '/api/public/media/resolve'
      preLoaderRoute: typeof ApiPublicMediaResolveRouteImport
      parentRoute: typeof ApiPublicMediaRoute
    }
    '/api/public/auth/status': {
      id: '/api/public/auth/status'
      path: '/api/public/auth/status'
      fullPath: '/api/public/auth/status'
      preLoaderRoute: typeof ApiPublicAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/pin': {
      id: '/api/public/auth/pin'
      path: '/api/public/auth/pin'
      fullPath: '/api/public/auth/pin'
      preLoaderRoute: typeof ApiPublicAuthPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/logout': {
      id: '/api/public/auth/logout'
      path: '/api/public/auth/logout'
      fullPath: '/api/public/auth/logout'
      preLoaderRoute: typeof ApiPublicAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicMediaRouteChildren {
  ApiPublicMediaResolveRoute: typeof ApiPublicMediaResolveRoute
}

const ApiPublicMediaRouteChildren: ApiPublicMediaRouteChildren = {
  ApiPublicMediaResolveRoute: ApiPublicMediaResolveRoute,
}

const ApiPublicMediaRouteWithChildren = ApiPublicMediaRoute._addFileChildren(
  ApiPublicMediaRouteChildren,
)

interface ApiPublicRedditRouteChildren {
  ApiPublicRedditMixRoute: typeof ApiPublicRedditMixRoute
  ApiPublicRedditUserRoute: typeof ApiPublicRedditUserRoute
}

const ApiPublicRedditRouteChildren: ApiPublicRedditRouteChildren = {
  ApiPublicRedditMixRoute: ApiPublicRedditMixRoute,
  ApiPublicRedditUserRoute: ApiPublicRedditUserRoute,
}

const ApiPublicRedditRouteWithChildren = ApiPublicRedditRoute._addFileChildren(
  ApiPublicRedditRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreatorNameRoute: CreatorNameRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
  ApiPublicMediaRoute: ApiPublicMediaRouteWithChildren,
  ApiPublicRedditRoute: ApiPublicRedditRouteWithChildren,
  ApiPublicAuthLogoutRoute: ApiPublicAuthLogoutRoute,
  ApiPublicAuthPinRoute: ApiPublicAuthPinRoute,
  ApiPublicAuthStatusRoute: ApiPublicAuthStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
