/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRedditRouteImport } from './routes/api/public/reddit'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as ApiPublicRedditMixRouteImport } from './routes/api/public/reddit/mix'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedditRoute = ApiPublicRedditRouteImport.update({
  id: '/api/public/reddit',
  path: '/api/public/reddit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRedditMixRoute = ApiPublicRedditMixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => ApiPublicRedditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/reddit': typeof ApiPublicRedditRouteWithChildren
  '/api/public/reddit/mix': typeof ApiPublicRedditMixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/reddit': typeof ApiPublicRedditRouteWithChildren
  '/api/public/reddit/mix': typeof ApiPublicRedditMixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/public/reddit': typeof ApiPublicRedditRouteWithChildren
  '/api/public/reddit/mix': typeof ApiPublicRedditMixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/image'
    | '/api/public/reddit'
    | '/api/public/reddit/mix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/image'
    | '/api/public/reddit'
    | '/api/public/reddit/mix'
  id:
    | '__root__'
    | '/'
    | '/api/public/image'
    | '/api/public/reddit'
    | '/api/public/reddit/mix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
  ApiPublicRedditRoute: typeof ApiPublicRedditRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reddit': {
      id: '/api/public/reddit'
      path: '/api/public/reddit'
      fullPath: '/api/public/reddit'
      preLoaderRoute: typeof ApiPublicRedditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reddit/mix': {
      id: '/api/public/reddit/mix'
      path: '/mix'
      fullPath: '/api/public/reddit/mix'
      preLoaderRoute: typeof ApiPublicRedditMixRouteImport
      parentRoute: typeof ApiPublicRedditRoute
    }
  }
}

interface ApiPublicRedditRouteChildren {
  ApiPublicRedditMixRoute: typeof ApiPublicRedditMixRoute
}

const ApiPublicRedditRouteChildren: ApiPublicRedditRouteChildren = {
  ApiPublicRedditMixRoute: ApiPublicRedditMixRoute,
}

const ApiPublicRedditRouteWithChildren = ApiPublicRedditRoute._addFileChildren(
  ApiPublicRedditRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
  ApiPublicRedditRoute: ApiPublicRedditRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
